In [2]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
from kalshi.events import Events

events = Events()
events = events.get_all_events(all_pages=True, status='open')
events_df = pd.DataFrame(events)
display(events_df.head())

In [ ]:
display(events_df.columns)

In [ ]:
display(events_df.describe().transpose())

In [ ]:
display(events_df['category'].value_counts())

In [ ]:
display(events_df[events_df['category'] == 'Sports'])

In [3]:
from kalshi.markets import Markets
from kalshi.utils import utc_to_local
markets = Markets()
list_markets = markets.get_all_markets(all_pages=False, status='open', mve_filter='exclude')
markets_df = pd.DataFrame(list_markets)
cols = markets_df.columns
for col in cols:
    if 'time' in col:
        markets_df[col] = markets_df[col].apply(utc_to_local)

In [4]:
display(markets_df.sort_values('close_time', ascending=True).head())

,can_close_early,close_time,created_time,custom_strike,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,fractional_trading_enabled,last_price_dollars,latest_expiration_time,liquidity_dollars,market_type,no_ask_dollars,no_bid_dollars,no_sub_title,notional_value_dollars,open_interest_fp,open_time,previous_price_dollars,previous_yes_ask_dollars,previous_yes_bid_dollars,price_level_structure,price_ranges,response_price_units,result,rules_primary,rules_secondary,settlement_timer_seconds,status,strike_type,subtitle,tick_size,ticker,title,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,floor_strike,primary_participant_key
21,True,2026-03-22 21:00:00-05:00,2026-03-20 15:20:36.001376-05:00,{'baseball_team': '40866f65-2c49-4221-81af-2f6...,This market will close and expire after a winn...,KXNCAABBGAME-26MAR202200WAHTRO,2026-03-21 02:00:00-05:00,2026-03-22 21:00:00-05:00,,False,0.0000,2026-03-22 21:00:00-05:00,0.0000,binary,0.2100,0.0400,USC,1.0000,0.00,2026-03-20 15:23:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If USC wins the Washington vs USC College Base...,"Kalshi is not affiliated, associated, authoriz...",1969-12-31 18:05:00-06:00,active,structured,,1,KXNCAABBGAME-26MAR202200WAHTRO-TRO,Washington vs USC winner?,2026-03-20 15:23:00.714382-05:00,0.00,0.00,0.9600,7792.00,0.7900,400.00,USC,NaN,NaN
20,True,2026-03-22 21:00:00-05:00,2026-03-20 15:20:36.001376-05:00,{'baseball_team': '8711ba15-dd1b-4d9e-b87e-3f4...,This market will close and expire after a winn...,KXNCAABBGAME-26MAR202200WAHTRO,2026-03-21 02:00:00-05:00,2026-03-22 21:00:00-05:00,,False,0.0000,2026-03-22 21:00:00-05:00,0.0000,binary,0.8800,0.7800,Washington,1.0000,0.00,2026-03-20 15:23:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Washington wins the Washington vs USC Colle...,"Kalshi is not affiliated, associated, authoriz...",1969-12-31 18:05:00-06:00,active,structured,,1,KXNCAABBGAME-26MAR202200WAHTRO-WAH,Washington vs USC winner?,2026-03-20 15:23:00.714382-05:00,0.00,0.00,0.2200,401.00,0.1200,400.00,Washington,NaN,NaN
49,True,2026-04-03 20:00:00-05:00,2026-03-20 15:02:47.616359-05:00,{'hockey_player': 'a6deb468-1c4b-4c8f-8b40-37b...,This market will close and expire early if the...,KXNHLFIRSTGOAL-26MAR20FLACGY,2026-03-20 23:00:00-05:00,2026-04-03 20:00:00-05:00,,False,0.0000,2026-04-03 20:00:00-05:00,0.0000,binary,1.0000,1.0000,Connor Zary,1.0000,0.00,2026-03-20 15:07:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Connor Zary scores the 1st goal in the FLA ...,The following market refers to a player in the...,1969-12-31 18:04:58-06:00,active,structured,,1,KXNHLFIRSTGOAL-26MAR20FLACGY-CGYCZARY47,Connor Zary: First Goalscorer,2026-03-20 15:07:00.752404-05:00,0.00,0.00,0.0000,0.00,0.0000,0.00,Connor Zary,NaN,hockey_player
72,True,2026-04-03 20:00:00-05:00,2026-03-20 15:02:46.388457-05:00,{'hockey_player': '4fa4f42d-cdf1-475f-a301-ae6...,This market will close and expire early if the...,KXNHLPTS-26MAR20FLACGY,2026-03-20 23:00:00-05:00,2026-04-03 20:00:00-05:00,,False,0.0000,2026-04-03 20:00:00-05:00,0.0000,binary,0.6500,0.5900,Matvei Gridin: 1+,1.0000,0.00,2026-03-20 15:07:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Matvei Gridin records at least 1+ points in...,The following market refers to a player in the...,1969-12-31 18:04:59-06:00,active,structured,,1,KXNHLPTS-26MAR20FLACGY-CGYMGRIDIN92-1,Matvei Gridin: 1+ points,2026-03-20 15:07:00.752404-05:00,0.00,0.00,0.4100,33.00,0.3500,400.00,Matvei Gridin: 1+,0.5,hockey_player
71,True,2026-04-03 20:00:00-05:00,2026-03-20 15:02:46.388457-05:00,{'hockey_player': '4fa4f42d-cdf1-475f-a301-ae6...,This market will close and expire early if the...,KXNHLPTS-26MAR20FLACGY,2026-03-20 23:00:00-05:00,2026-04-03 20:00:00-05:00,,False,0.0000,2026-04-03 20:00:00-05:00,0.0000,binary,1.0000,1.0000,Matvei Gridin: 2+,1.0000,0.00,2026-03-20 15:07:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Matvei Gridin records at least 2+ points in...,The following market refers to a player in the...,1969-12-31 18:04:59-06:00,active,structured,,1,KXNHLPTS-26MAR20FLACGY-CGYMGRIDIN92-2,Matvei Gridin: 2+ points,2026-03-20 15:07:00.752404-05:00,0.00,0.00,0.0000,0.00,0.0000,0.00,Matvei Gridin: 2+,1.5,hockey_player

In [12]:
display(markets_df)

,can_close_early,close_time,created_time,custom_strike,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,fractional_trading_enabled,last_price_dollars,latest_expiration_time,liquidity_dollars,market_type,no_ask_dollars,no_bid_dollars,no_sub_title,notional_value_dollars,open_interest_fp,open_time,previous_price_dollars,previous_yes_ask_dollars,previous_yes_bid_dollars,price_level_structure,price_ranges,response_price_units,result,rules_primary,rules_secondary,settlement_timer_seconds,status,strike_type,subtitle,tick_size,ticker,title,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,floor_strike,primary_participant_key
0,True,2026-04-04 13:30:00-05:00,2026-03-20 15:41:00.858689-05:00,{'esports_competitor': '039ed30e-a367-4eca-be1...,This market will close and expire after a winn...,KXVALORANTMAP-26MAR21GNGMDR-2,2026-03-21 17:30:00-05:00,2026-04-04 13:30:00-05:00,,False,0.0000,2026-04-04 13:30:00-05:00,0.0000,binary,0.9900,0.0100,Mandatory,1.0000,0.00,2026-03-20 15:55:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Mandatory wins map 2 in the VCL EMEA: 2026:...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXVALORANTMAP-26MAR21GNGMDR-2-MDR,Will Mandatory win map 2 in the GnG Amazigh vs...,2026-03-20 15:55:00.714690-05:00,0.00,0.00,0.9900,661.00,0.0100,661.00,Mandatory,NaN,NaN
1,True,2026-04-04 13:30:00-05:00,2026-03-20 15:41:00.858689-05:00,{'esports_competitor': 'b069d015-6cae-4e71-b68...,This market will close and expire after a winn...,KXVALORANTMAP-26MAR21GNGMDR-2,2026-03-21 17:30:00-05:00,2026-04-04 13:30:00-05:00,,False,0.0000,2026-04-04 13:30:00-05:00,0.0000,binary,0.9900,0.0100,GnG Amazigh,1.0000,0.00,2026-03-20 15:55:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If GnG Amazigh wins map 2 in the VCL EMEA: 202...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXVALORANTMAP-26MAR21GNGMDR-2-GNG,Will GnG Amazigh win map 2 in the GnG Amazigh ...,2026-03-20 15:55:00.714690-05:00,0.00,0.00,0.9900,661.00,0.0100,661.00,GnG Amazigh,NaN,NaN
2,True,2026-04-04 13:30:00-05:00,2026-03-20 15:41:00.307873-05:00,{'esports_competitor': '039ed30e-a367-4eca-be1...,This market will close and expire after a winn...,KXVALORANTMAP-26MAR21GNGMDR-1,2026-03-21 17:30:00-05:00,2026-04-04 13:30:00-05:00,,False,0.0000,2026-04-04 13:30:00-05:00,0.0000,binary,0.9900,0.0100,Mandatory,1.0000,0.00,2026-03-20 15:55:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Mandatory wins map 1 in the VCL EMEA: 2026:...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXVALORANTMAP-26MAR21GNGMDR-1-MDR,Will Mandatory win map 1 in the GnG Amazigh vs...,2026-03-20 15:55:00.714690-05:00,0.00,0.00,0.9900,661.00,0.0100,661.00,Mandatory,NaN,NaN
3,True,2026-04-04 13:30:00-05:00,2026-03-20 15:41:00.307873-05:00,{'esports_competitor': 'b069d015-6cae-4e71-b68...,This market will close and expire after a winn...,KXVALORANTMAP-26MAR21GNGMDR-1,2026-03-21 17:30:00-05:00,2026-04-04 13:30:00-05:00,,False,0.0000,2026-04-04 13:30:00-05:00,0.0000,binary,0.9900,0.0100,GnG Amazigh,1.0000,0.00,2026-03-20 15:55:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If GnG Amazigh wins map 1 in the VCL EMEA: 202...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXVALORANTMAP-26MAR21GNGMDR-1-GNG,Will GnG Amazigh win map 1 in the GnG Amazigh ...,2026-03-20 15:55:00.714690-05:00,0.00,0.00,0.9900,661.00,0.0100,661.00,GnG Amazigh,NaN,NaN
4,True,2026-04-04 13:30:00-05:00,2026-03-20 15:32:10.972756-05:00,{'esports_competitor': '039ed30e-a367-4eca-be1...,This market will close and expire after a winn...,KXVALORANTGAME-26MAR21GNGMDR,2026-03-21 17:30:00-05:00,2026-04-04 13:30:00-05:00,,False,0.0000,2026-04-04 13:30:00-05:00,0.0000,binary,0.9300,0.1600,Mandatory,1.0000,0.00,2026-03-20 15:37:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Mandatory wins the VCL EMEA: 2026: GnG Amaz...,,1969-12-31 18:01:58-06:00,active,structured,,1,KXVALORANTGAME-26MAR21GNGMDR-MDR,Will Mandatory win the GnG Amazigh vs. Mandato...,2026-03-20 15:37:00.714168-05:00,0.00,0.00,0.8400,20.00,0.0700,10.00,Mandatory,NaN,NaN
5,True,2026-04-04 13:30:00-05:00,2026-03-20 15:32:10.972756-05:00,{'esports_competitor': 'b069d015-6cae-4e71-b68...,This market will close and expire after a winn...,KXVALORANTGAME-26MAR21GNGMDR,2026-03-21 17:30:00-05:00,2026-04-04 13:30:00-05:00,,False,0.0000,2026-04-04 13:30:00-05:00,0.0000,binary,0.9300,0.1600,GnG Amazigh,1.0000,0.00,2026-03-20 15:37:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If GnG Amazigh wins the VCL EMEA: 2026: GnG Am...,,1969-12-31 18:01:58-06:00,active,structured,,1,KXVALORANTGAME-26MAR21GNGMDR-GNG,Will GnG Amazigh win the GnG Amazigh vs. Manda...,2026-03-20 15:37:00.714168-05:00,0.00,0.00,0.8400,20.00,0.0700,10.00,GnG Amazigh,NaN,NaN
6,True,2026-04-04 13:00:00-05:00,2026-03-20 15:31:01.186189-05:00,{'esports_competitor': 'e7b6d585-4698-46e9-b43...,This market will close and expire after a winn...,KXLOLMAP-26MAR21JDGBLG-3,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.7300,0.6500,JD Gaming,1.0000,0.00,2026-03-20 15:45:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If JD Gaming wins map 3 in the First Stand 202...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXLOLMAP-26MAR21JDGBLG-3-JDG,Will JD Gaming win map 3 in the JD Gaming vs. ...,2026-03-20 15:45:00.714189-05:00,0.00,0.00,0.3500,500.00,0.2700,750.00,JD Gaming,NaN,NaN
7,True,2026-04-04 13:00:00-05:00,2026-03-20 15:31:01.186189-05:00,{'esports_competitor': '1942e522-e098-4311-8f0...,This market will close and expire after a winn...,KXLOLMAP-26MAR21JDGBLG-3,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.3500,0.2200,Bilibili Gaming,1.0000,0.00,2026-03-20 15:45:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Bilibili Gaming wins map 3 in the First Sta...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXLOLMAP-26MAR21JDGBLG-3-BLG,Will Bilibili Gaming win map 3 in the JD Gamin...,2026-03-20 15:45:00.714189-05:00,0.00,0.00,0.7800,500.00,0.6500,500.00,Bilibili Gaming,NaN,NaN
8,True,2026-04-04 13:00:00-05:00,2026-03-20 15:31:00.568453-05:00,{'esports_competitor': 'e7b6d585-4698-46e9-b43...,This market will close and expire after a winn...,KXLOLMAP-26MAR21JDGBLG-2,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.7300,0.6500,JD Gaming,1.0000,0.00,2026-03-20 15:45:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If JD Gaming wins map 2 in the First Stand 202...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXLOLMAP-26MAR21JDGBLG-2-JDG,Will JD Gaming win map 2 in the JD Gaming vs. ...,2026-03-20 15:45:00.714189-05:00,0.00,0.00,0.3500,500.00,0.2700,750.00,JD Gaming,NaN,NaN
9,True,2026-04-04 13:00:00-05:00,2026-03-20 15:31:00.568453-05:00,{'esports_competitor': '1942e522-e098-4311-8f0...,This market will close and expire after a winn...,KXLOLMAP-26MAR21JDGBLG-2,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.3500,0.2200,Bilibili Gaming,1.0000,0.00,2026-03-20 15:45:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Bilibili Gaming wins map 2 in the First Sta...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXLOLMAP-26MAR21JDGBLG-2-BLG,Will Bilibili Gaming win map 2 in the JD Gamin...,2026-03-20 15:45:00.714189-05:00,0.00,0.00,0.7800,500.00,0.6500,500.00,Bilibili Gaming,NaN,NaN
10,True,2026-04-04 13:00:00-05:00,2026-03-20 15:30:59.967323-05:00,{'esports_competitor': 'e7b6d585-4698-46e9-b43...,This market will close and expire after a winn...,KXLOLMAP-26MAR21JDGBLG-1,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.7300,0.6500,JD Gaming,1.0000,0.00,2026-03-20 15:45:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If JD Gaming wins map 1 in the First Stand 202...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXLOLMAP-26MAR21JDGBLG-1-JDG,Will JD Gaming win map 1 in the JD Gaming vs. ...,2026-03-20 15:45:00.714189-05:00,0.00,0.00,0.3500,500.00,0.2700,750.00,JD Gaming,NaN,NaN
11,True,2026-04-04 13:00:00-05:00,2026-03-20 15:30:59.967323-05:00,{'esports_competitor': '1942e522-e098-4311-8f0...,This market will close and expire after a winn...,KXLOLMAP-26MAR21JDGBLG-1,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.3500,0.2200,Bilibili Gaming,1.0000,0.00,2026-03-20 15:45:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Bilibili Gaming wins map 1 in the First Sta...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXLOLMAP-26MAR21JDGBLG-1-BLG,Will Bilibili Gaming win map 1 in the JD Gamin...,2026-03-20 15:45:00.714189-05:00,0.00,0.00,0.7800,500.00,0.6500,500.00,Bilibili Gaming,NaN,NaN
12,True,2026-04-04 13:00:00-05:00,2026-03-20 15:30:52.133905-05:00,NaN,This market will close and expire after the ev...,KXLOLTOTALMAPS-26MAR21JDGBLG,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.7600,0.6800,Over 4.5 maps,1.0000,0.00,2026-03-20 15:35:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If over 4.5 maps are played in the First Stand...,,1969-12-31 18:01:59-06:00,active,greater,,1,KXLOLTOTALMAPS-26MAR21JDGBLG-5,Will over 4.5 maps be played in the JD Gaming ...,2026-03-20 15:35:00.714556-05:00,0.00,0.00,0.3200,500.00,0.2400,500.00,Over 4.5 maps,4.5,NaN
13,True,2026-04-04 13:00:00-05:00,2026-03-20 15:30:52.133905-05:00,NaN,This market will close and expire after the ev...,KXLOLTOTALMAPS-26MAR21JDGBLG,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.4300,0.3500,Over 3.5 maps,1.0000,0.00,2026-03-20 15:35:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If over 3.5 maps are played in the First Stand...,,1969-12-31 18:01:59-06:00,active,greater,,1,KXLOLTOTALMAPS-26MAR21JDGBLG-4,Will over 3.5 maps be played in the JD Gaming ...,2026-03-20 15:35:00.714556-05:00,0.00,0.00,0.6500,500.00,0.5700,507.00,Over 3.5 maps,3.5,NaN
14,True,2026-04-04 09:00:00-05:00,2026-03-20 15:24:02.776794-05:00,{'tennis_competitor': 'af6bf52a-0c5a-48c9-9deb...,This market will close and expire after a winn...,KXWTAMATCH-26MAR21SHNBEN,2026-03-21 12:00:00-05:00,2026-04-04 09:00:00-05:00,,False,0.0000,2026-04-04 09:00:00-05:00,0.0000,binary,0.9100,0.2100,Diana Shnaider,1.0000,0.00,2026-03-20 15:27:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Diana Shnaider wins the Shnaider vs Bencic ...,The following market refers to the Shnaider vs...,1969-12-31 18:01:00-06:00,active,structured,,1,KXWTAMATCH-26MAR21SHNBEN-SHN,Will Diana Shnaider win the Shnaider vs Bencic...,2026-03-20 15:27:00.714587-05:00,0.00,0.00,0.7900,10.00,0.0900,10.00,Diana Shnaider,NaN,NaN
15,True,2026-04-04 09:00:00-05:00,2026-03-20 15:24:02.776794-05:00,{'tennis_competitor': '694b63b8-6c41-4148-a4f8...,This market will close and expire after a winn...,KXWTAMATCH-26MAR21SHNBEN,2026-03-21 12:00:00-05:00,2026-04-04 09:00:00-05:00,,False,0.0000,2026-04-04 09:00:00-05:00,0.0000,binary,0.9100,0.2100,Belinda Bencic,1.0000,0.00,2026-03-20 15:27:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Belinda Bencic wins the Shnaider vs Bencic ...,The following market refers to the Shnaider vs...,1969-12-31 18:01:00-06:00,active,structured,,1,KXWTAMATCH-26MAR21SHNBEN-BEN,Will Belinda Bencic win the Shnaider vs Bencic...,2026-03-20 15:27:00.714587-05:00,0.00,0.00,0.7900,10.00,0.0900,10.00,Belinda Bencic,NaN,NaN
16,True,2026-04-04 09:00:00-05:00,2026-03-20 15:24:02.419506-05:00,{'tennis_competitor': '8205fc30-c34f-4359-a99e...,This market will close and expire after a winn...,KXWTAMATCH-26MAR21ZAKMBO,2026-03-21 12:00:00-05:00,2026-04-04 09:00:00-05:00,,False,0.0000,2026-04-04 09:00:00-05:00,0.0000,binary,0.9100,0.2100,Anastasia Zakharova,1.0000,0.00,2026-03-20 15:27:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Anastasia Zakharova wins the Zakharova vs M...,The following market refers to the Zakharova v...,1969-12-31 18:01:00-06:00,active,structured,,1,KXWTAMATCH-26MAR21ZAKMBO-ZAK,Will Anastasia Zakharova win the Zakharova vs ...,2026-03-20 15:27:00.714587-05:00,0.00,0.00,0.7900,10.00,0.0900,10.00,Anastasia Zakharova,NaN,NaN
17,True,2026-04-04 09:00:00-05:00,2026-03-20 15:24:02.419506-05:00,{'tennis_competitor': '614cf010-1491-4c35-a153...,This market will close and expire after a winn...,KXWTAMATCH-26MAR21ZAKMBO,2026-03-21 12:00:00-05:00,2026-04-04 09:00:00-05:00,,False,0.0000,2026-04-04 09:00:00-05:00,0.0000,binary,0.9100,0.2100,Victoria Mboko,1.0000,0.00,2026-03-20 15:27:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Victoria Mboko wins the Zakharova vs Mboko ...,The following market refers to the Zakharova v...,1969-12-31 18:01:00-06:00,active,structured,,1,KXWTAMATCH-26MAR21ZAKMBO-MBO,Will Victoria Mboko win the Zakharova vs Mboko...,2026-03-20 15:27:00.714587-05:00,0.00,0.00,0.7900,10.00,0.0900,10.00,Victoria Mboko,NaN,NaN
18,True,2026-04-04 13:00:00-05:00,2026-03-20 15:21:17.862151-05:00,{'esports_competitor': 'e7b6d585-4698-46e9-b43...,This market will close and expire after a winn...,KXLOLGAME-26MAR21JDGBLG,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.0000,2026-04-04 13:00:00-05:00,0.0000,binary,0.8400,0.8100,JD Gaming,1.0000,0.00,2026-03-20 15:25:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If JD Gaming wins the First Stand 2026: JD Gam...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXLOLGAME-26MAR21JDGBLG-JDG,Will JD Gaming win the JD Gaming vs. Bilibili ...,2026-03-20 15:25:00.715005-05:00,0.00,0.00,0.1900,2000.00,0.1600,500.00,JD Gaming,NaN,NaN
19,True,2026-04-04 13:00:00-05:00,2026-03-20 15:21:17.862151-05:00,{'esports_competitor': '1942e522-e098-4311-8f0...,This market will close and expire after a winn...,KXLOLGAME-26MAR21JDGBLG,2026-03-21 17:00:00-05:00,2026-04-04 13:00:00-05:00,,False,0.7900,2026-04-04 13:00:00-05:00,0.0000,binary,0.2300,0.2100,Bilibili Gaming,1.0000,26.00,2026-03-20 15:25:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Bilibili Gaming wins the First Stand 2026: ...,,1969-12-31 18:01:59-06:00,active,structured,,1,KXLOLGAME-26MAR21JDGBLG-BLG,Will Bilibili Gaming win the JD Gaming vs. Bil...,2026-03-20 15:25:00.715005-05:00,26.00,26.00,0.7900,4.00,0.7700,500.00,Bilibili Gaming,NaN,NaN
20,True,2026-03-22 21:00:00-05:00,2026-03-20 15:20:36.001376-05:00,{'baseball_team': '8711ba15-dd1b-4d9e-b87e-3f4...,This market will close and expire after a winn...,KXNCAABBGAME-26MAR202200WAHTRO,2026-03-21 02:00:00-05:00,2026-03-22 21:00:00-05:00,,False,0.0000,2026-03-22 21:00:00-05:00,0.0000,binary,0.8800,0.7800,Washington,1.0000,0.00,2026-03-20 15:23:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Washington wins the Washington vs USC Colle...,"Kalshi is not affiliated, associated, authoriz...",1969-12-31 18:05:00-06:00,active,structured,,1,KXNCAABBGAME-26MAR202200WAHTRO-WAH,Washington vs USC winner?,2026-03-20 15:23:00.714382-05:00,0.00,0.00,0.2200,401.00,0.1200,400.00,Washington,NaN,NaN
21,True,2026-03-22 21:00:00-05:00,2026-03-20 15:20:36.001376-05:00,{'baseball_team': '40866f65-2c49-4221-81af-2f6...,This market will close and expire after a winn...,KXNCAABBGAME-26MAR202200WAHTRO,2026-03-21 02:00:00-05:00,2026-03-22 21:00:00-05:00,,False,0.0000,2026-03-22 21:00:00-05:00,0.0000,binary,0.2100,0.0400,USC,1.0000,0.00,2026-03-20 15:23:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If USC wins the Washington vs USC College Base...,"Kalshi is not affiliated, associated, authoriz...",1969-12-31 18:05:00-06:00,active,structured,,1,KXNCAABBGAME-26MAR202200WAHTRO-TRO,Washington vs USC winner?,2026-03-20 15:23:00.714382-05:00,0.00,0.00,0.9600,7792.00,0.7900,400.00,USC,NaN,NaN
22,True,2026-04-03 20:00:00-05:00,2026-03-20 15:02:47.616359-05:00,{'hockey_player': '5fe03ab6-d9cd-41b8-a108-9ab...,This market will close and expire early if the...,KXNHLFIRSTGOAL-26MAR20FLACGY,2026-03-20 23:00:00-05:00,2026-04-03 20:00:00-05:00,,False,0.0000,2026-04-03 20:00:00-05:00,0.0000,binary,1.0000,0.0000,Tomas Nosek,1.0000,0.00,2026-03-20 15:07:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Tomas Nosek scores the 1st goal in the FLA ...,The following market refers to a player in the...,1969-12-31 18:04:58-06:00,active,structured,,1,KXNHLFIRSTGOAL-26MAR20FLACGY-FLATNOSEK92,Tomas Nosek: First Goalscorer,2026-03-20 15:07:00.752404-05:00,0.00,0.00,1.0000,0.00,0.0000,0.00,Tomas Nosek,NaN,hockey_player
23,True,2026-04-03 20:00:00-05:00,2026-03-20 15:02:47.616359-05:00,{'hockey_player': '14e76c50-6c29-4da3-ace8-6ab...,This market will close and expire early if the...,KXNHLFIRSTGOAL-26MAR20FLACGY,2026-03-20 23:00:00-05:00,2026-04-03 20:00:00-05:00,,False,0.0000,2026-04-03 20:00:00-05:00,0.0000,binary,1.0000,1.0000,Seth Jones,1.0000,0.00,2026-03-20 15:07:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Seth Jones scores the 1st goal in the FLA P...,The following market refers to a player in the...,1969-12-31 18:04:58-06:00,active,structured,,1,KXNHLFIRSTGOAL-26MAR20FLACGY-FLASJONES3,Seth Jones: First Goalscorer,2026-03-20 15:07:00.752404-05:00,0.00,0.00,0.0000,0.00,0.0000,0.00,Seth Jones,NaN,hockey_player
24,True,2026-04-03 20:00:00-05:00,2026-03-20 15:02:47.616359-05:00,{'hockey_player': '713436d4-b2ec-4af5-907b-9f9...,This market will close and expire early if the...,KXNHLFIRSTGOAL-26MAR20FLACGY,2026-03-20 23:00:00-05:00,2026-04-03 20:00:00-05:00,,False,0.0000,2026-04-03 20:00:00-05:00,0.0000,binary,1.0000,1.0000,Sam Bennett,1.0000,0.00,2026-03-20 15:07:00-05:00,0.0000,0.0000,0.0000,linear_cent,"[{'end': '1.0000', 'start': '0.0000', 'step': ...",usd_cent,,If Sam Bennett scores the 1st goal in the FLA ...,The following market refers to a player in the...,1969-12-31 18:04:58-06:00,active,structured,,1,KXNHLFIRSTGOAL-26MAR20FLACGY-FLASBENNETT9,Sam Bennett: First Goalscorer,2026-03-20 15:07:00.752404-05:00,0.00,0.00,0.0000,0.00,0.0000,0.00,Sam Bennett,NaN,hockey_player

In [6]:
display(markets_df.describe().transpose())

              count  mean       std  min  25%  50%  75%  max
tick_size     100.0  1.00  0.000000  1.0  1.0  1.0  1.0  1.0
floor_strike   50.0  1.48  0.936559  0.5  0.5  1.5  2.5  4.5

In [7]:
display(markets_df.describe().transpose())

              count  mean       std  min  25%  50%  75%  max
tick_size     100.0  1.00  0.000000  1.0  1.0  1.0  1.0  1.0
floor_strike   50.0  1.48  0.936559  0.5  0.5  1.5  2.5  4.5

In [8]:
orderbook = markets.get_market_orderbook('KXNCAABBGAME-26MAR202130LBSCBR-CBR')

In [9]:
display(orderbook)

{'orderbook_fp': {'no_dollars': [['0.0100', '1461.00'],
   ['0.0200', '150.00'],
   ['0.0300', '25.00']],
  'yes_dollars': [['0.0100', '1561.00'],
   ['0.0200', '200.00'],
   ['0.0300', '50.00']]}}

In [10]:
market_trades = markets.get_market_trades('KXNCAABBGAME-26MAR202130LBSCBR-CBR')

In [11]:
display(market_trades)

[]